### ISSUE TITLE
InverseProperty behaves differently depending on which side of the relationship it is applied

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#184]
I was under the impression one could apply `InversePropertyAttribute` to either side of the relationship (but not both) and it would work the same. But I found this not to be true whilst putting together a repro for a different problem :)

Consider this:
```C#
[Entity]
public interface IQuote
{
    string Id
    {
        get;
    }

    //[InverseProperty("Quote")]
    ICollection<IQuoteItem> Items
    {
        get;
        set;
    }
}

[Entity]
public interface IQuoteItem
{
    string Id
    {
        get;
    }

    string Name
    {
        get;
        set;
    }

    [InverseProperty("Items")]
    IQuote Quote
    {
        get;
        set;
    }
}

using (var context = new MyEntityContext(connectionString))
{
    var quote = new Quote
    {
        Items = new[]
        { 
            new QuoteItem
            {
                Name = "First"
            },
            new QuoteItem
            {
                Name = "Second"
            },
            new QuoteItem
            {
                Name = "Third"
            },
        }
    };

    context.Quotes.Add(quote);
    context.SaveChanges();
}
```
As it stands, the call to add the quote fails with:
```
System.ArgumentNullException was unhandled by user code
  HResult=-2147467261
  Message=Value cannot be null.
Parameter name: value
  Source=BrightstarDB
  ParamName=value
  StackTrace:
       at BrightstarDB.Client.DataObject.AddProperty(IDataObject type, Object value, String lang)
       at BrightstarDB.Client.DataObject.AddProperty(String type, Object value, String lang)
       at BrightstarDB.EntityFramework.BrightstarEntityObject.SetRelatedObjects[T](String propertyName, ICollection`1 relatedObjects)
       at BrightstarDB_REPRO.Quote.set_Items(ICollection`1 value)
```
On a gut feeling I moved the `InverseProperty` to the `Items` property instead and then it worked. At least, it doesn't throw. The items don't get saved with the quote so now I'm trying to figure out why that might be...

**Comment by kal** [comment]
It should work either way. They will result in different structures in the datastore, so you can't chop and change once your data is set up, but it should be possible to run the code as you had it here. This sounds like a bug I'll need to look into.
