### ISSUE TITLE
Where clause comparing identifier to null throws

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#189]
If a where clause compares an entity's identifier to `null`, an exception is thrown. Example code:
```C#
[Entity]
public interface IEntity
{
    string Id
    {
        get;
    }
}

using (var context = new MyEntityContext(connectionString))
{
    var existing = context
        .Entities
        .Where(x => x.Id == null)
        .FirstOrDefault();
}
```
Exception trace:
```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=BrightstarDB
  StackTrace:
       at BrightstarDB.EntityFramework.Query.SparqlGeneratorQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at BrightstarDB.EntityFramework.Query.SparqlGeneratorQueryModelVisitor.GenerateSparqlLinqQuery(EntityContext context, QueryModel queryModel)
       at BrightstarDB.EntityFramework.Query.EntityFrameworkQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
       at BrightstarDB.EntityFramework.Query.EntityFrameworkQueryExecutor.ExecuteSingle[T](QueryModel queryModel, Boolean returnDefaultWhenEmpty)
       at Remotion.Linq.Clauses.StreamedData.StreamedSingleValueInfo.ExecuteSingleQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
       at Remotion.Linq.Clauses.StreamedData.StreamedSingleValueInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
       at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
       at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
       at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
       at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
       at BrightstarDB_REPRO.Program.Main(String[] args) in \\psf\home\Documents\Visual Studio 2013\Projects\BrightstarDB_REPRO\Program.cs:line 30
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```
My specific use case looks like this:
```C#
private static bool AddOrUpdateSubstitution(EntityContext entityContext, ISubstitutionEntity substitution)
{
    var existingSubstitution = entityContext
        .SubstitutionEntities
        .Where(x => x.Id == substitution.Id)
        .FirstOrDefault();

    if (existingSubstitution != null)
    {
        entityContext.DeleteObject(existingSubstitution);
    }

    entityContext.SubstitutionEntities.Add(substitution);
    return existingSubstitution == null;
}
```
If the substitution is new, it has a `null` ID, so the resolution of `existingSubstitution` fails. As a hacky interim workaround, I have this:
```C#
var existingSubstitution = entityContext
    .SubstitutionEntities
    .Where(x => x.Id == (substitution.Id ?? string.Empty))
    .FirstOrDefault();
```

**Comment by kal** [comment]
Entities cannot be stored in a context with no ID, so the Id property cannot be null and it would not be possible to create a meaningful SPARQL query  in such a case. It would be better if the LINQ processing code throws a specific error for this, but in general I think this is something you need to work around in the data access layer. In your specific case, you can assume that if substiution.Id == null, then the query would never return anything so just skip the query and Delete and move straight to the Add.

**Comment by kentcb** [comment]
Hmm, I understand, but this results in this rather convoluted code:
```C#
private static bool AddOrUpdateQuote(EntityContext entityContext, IQuoteEntity quote)
{
    IQuoteEntity existingQuote = null;

    if (quote.Reference != null)
    {
        existingQuote = entityContext
            .QuoteEntities
            .Where(x => x.Reference == quote.Reference)
            .FirstOrDefault();

        if (existingQuote != null)
        {
            entityContext.DeleteObject(existingQuote);
        }
    }

    entityContext.QuoteEntities.Add(quote);
    return existingQuote == null;
}
```
Is it possible to add an `AddOrUpdate()` method to `IEntitySet<T>`? This seems like such a common requirement to me that it would be nice to manifest it in the framework somehow...it would be nice to instead be able to:
```C#
entityContext
    .QuoteEntities
    .AddOrUpdate(quote);
```

**Comment by kal** [comment]
Providing an AddOrUpdate method sounds like a good idea to me. I'll open a separate issue for that as an enhancement request.
