### ISSUE TITLE
Template execution error under VS2015

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#198]
Hi,

I'm getting this error when attempting to execute the T4 template under VS2015 (CTP 5):
```
Running transformation: System.NotImplementedException: Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelProjectCache.GetOrCreateFileCodeModel(String fileName, Object parent)
   at Microsoft.VisualStudio.LanguageServices.CSharp.ProjectSystemShim.CSharpProjectShimWithServices.CreateFileCodeModel(String fileName, Object parent, FileCodeModel& ppFileCodeModel)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeParameter.LookupNode()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.Collections.AttributeCollection.get_Count()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.Collections.CodeElementSnapshot..ctor(ICodeElements codeElements)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.Collections.AbstractCodeElementCollection.CreateSnapshot()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.Collections.AbstractCodeElementCollection.GetEnumerator()
   at EnvDTE.CodeElements.GetEnumerator()
   at Microsoft.VisualStudio.TextTemplatingAB9F0685D4D4E0001DA41248F091EB1231114C3E93CA9EAB4C2EE7C52B59988F0167442BB4D6533E60D215740997866F3CD4A0BF2385D364E97A393F8D57E9AF.GeneratedTextTransformation.Helper.<GetInterfaces>d__3c.MoveNext() in y:\SNIP\EntityContext.tt:line 673
   at Microsoft.VisualStudio.TextTemplatingAB9F0685D4D4E0001DA41248F091EB1231114C3E93CA9EAB4C2EE7C52B59988F0167442BB4D6533E60D215740997866F3CD4A0BF2385D364E97A393F8D57E9AF.GeneratedTextTransformation.Helper.<GetInterfaces>d__3c.MoveNext() in y:\SNIP\EntityContext.tt:line 677
   at Microsoft.VisualStudio.TextTemplatingAB9F0685D4D4E0001DA41248F091EB1231114C3E93CA9EAB4C2EE7C52B59988F0167442BB4D6533E60D215740997866F3CD4A0BF2385D364E97A393F8D57E9AF.GeneratedTextTransformation.Helper.<GetInterfaces>d__3c.MoveNext() in y:\SNIP\EntityContext.tt:line 677
   at Microsoft.VisualStudio.TextTemplatingAB9F0685D4D4E0001DA41248F091EB1231114C3E93CA9EAB4C2EE7C52B59988F0167442BB4D6533E60D215740997866F3CD4A0BF2385D364E97A393F8D57E9AF.GeneratedTextTransformation.Helper.<GetInterfaces>d__3c.MoveNext() in y:\SNIP\EntityContext.tt:line 677
   at Microsoft.VisualStudio.TextTemplatingAB9F0685D4D4E0001DA41248F091EB1231114C3E93CA9EAB4C2EE7C52B59988F0167442BB4D6533E60D215740997866F3CD4A0BF2385D364E97A393F8D57E9AF.GeneratedTextTransformation.Helper.<GetInterfaces>d__3c.MoveNext() in y:\SNIP\EntityContext.tt:line 677
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TextTemplatingAB9F0685D4D4E0001DA41248F091EB1231114C3E93CA9EAB4C2EE7C52B59988F0167442BB4D6533E60D215740997866F3CD4A0BF2385D364E97A393F8D57E9AF.GeneratedTextTransformation.Helper.<GetExtraUsings>b__29(ProjectItem pi) in y:\SNIP\EntityContext.tt:line 635
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__8`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__22`1.MoveNext()
   at System.Linq.Enumerable.<ExceptIterator>d__25`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TextTemplatingAB9F0685D4D4E0001DA41248F091EB1231114C3E93CA9EAB4C2EE7C52B59988F0167442BB4D6533E60D215740997866F3CD4A0BF2385D364E97A393F8D57E9AF.GeneratedTextTransformation.TransformText() in y:\SNIP\EntityContext.tt:line 19	
```
The same template in the same project executes fine under VS2013.

**Comment by kentcb** [comment]
I'm getting the same thing now under VS2013, probably because I restarted my machine.

:fearful:

**Comment by kal** [comment]
I don't get this in VS2013 on a machine without VS2015 installed. My guess is that its a bug with the VS2015 preview / CTP that you have installed. And I'm now a bit wary about installing it myself!

**Comment by kal** [comment]
Maybe review this when a final VS2015 release is available?

**Comment by kentcb** [comment]
FYI, I started a PR yesterday to switch the codegen over to Roslyn and offer a command line alternative to the T4 gen. Will support VB too. Will submit the PR probably later this week.

I am completely blocked atm because my codegen doesn't even work in 2013 anymore (even on a machine without 2015).

**Comment by kal** [comment]
Sounds cool! I guess it will have to be in addition to the current T4 approach for 1.11... but hopefully 2.0 can ditch T4 in favor of Roslyn-based code generation.

**Comment by kal** [comment]
This was an issue for me too with CTP 6, but with the new VS 2015 RC the ENVDTE-based text template now runs fine.
