### ISSUE TITLE
Getting "Error creating store test. Store already exists" when creating context

### ISSUE THREAD

**Issue by cjochoa** [BrightstarDB/BrightstarDB#293]
Hi, I am following the examples creating entities and context, and I get the following exception on the second attempt to create a context (after deleting the store in my unit testing setup)

Result StackTrace:	
at BrightstarDB.Client.EmbeddedBrightstarService.CreateStore(String storeName, PersistenceType persistenceType)
   at BrightstarDB.Client.EmbeddedBrightstarService.CreateStore(String storeName)
   at BrightstarDB.EntityFramework.BrightstarEntityContext.AssertStoreFromConnectionString(ConnectionString connectionString)
   at BrightstarDB.EntityFramework.BrightstarEntityContext..ctor(String connectionString, Nullable`1 enableOptimisticLocking, String updateGraphUri, IEnumerable`1 datasetGraphUris, String versionGraphUri, Nullable`1 enableFilterOptimization)
   at XXXContext..ctor(String connectionString, Nullable`1 enableOptimisticLocking, String updateGraphUri, IEnumerable`1 datasetGraphUris, String versionGraphUri) in ...
--StoreManagerException
   at BrightstarDB.Storage.BPlusTreeStore.BPlusTreeStoreManager.CreateStore(String storeLocation, PersistenceType storePersistenceType, Boolean readOnly, Boolean withTransactionLogging)
   at BrightstarDB.Server.ServerCore.CreateStore(String storeName, PersistenceType persistenceType)
   at BrightstarDB.Client.EmbeddedBrightstarService.CreateStore(String storeName, PersistenceType persistenceType)
Result Message:	
BrightstarDB.Client.BrightstarClientException : Error creating store test. Store already exists
  ----> BrightstarDB.Storage.StoreManagerException : Store already exists

**Comment by osc117** [comment]
You need to delete the folder containing the store to

**Comment by cjochoa** [comment]
Thanks, deleting the folder did the trick!
