### ISSUE TITLE
Connecting to non-localhost BS* service via REST

### ISSUE THREAD

**Issue by mylesdunlop** [BrightstarDB/BrightstarDB#298]
This might be a documentation issue, or at least one that I've been unable to locate any specific documentation on.

I have an application that has been successfully tested in two modes:
a) Connecting to an embedded data store i.e. type=embedded;storesdirectory=c:\mypath;storename=mystorename
b) Connecting to a BS service on localhost i.e. type=rest;endpoint=http://localhost:8090/brightstar;storename=mystorename

Following on from b), the issue is I've been unable to gain successful operation when connecting to a non-localhost server i.e. another PC or VM on a home-office LAN. The client system is Windows 7 x64, whereas the server system is an Windows 7 x86 VM or Windows 10 x64 laptop (doesn't seem to make any difference which).

Provided I turn off the Windows Firewall on the server system, I can connect to the remote data store fine using Polaris and can sort of intermittently connect using the developed application (and very occasionally perform some data retrieval operation), but as a general rule data store operations will just timeout after a minute or two. It doesn't seem to make any difference whether I specify user credentials in the connection string.

How should the client/server systems be configured? To my thinking this is quite an obvious mode of operation, yet it doesn't seem to be documented other than in a basic way in: http://brightstardb.readthedocs.io/en/latest/Connection_Strings/. 
Perhaps I have missed some really obvious point...

**Comment by kal** [comment]
This is really strange - it's not a problem that I've seen before. Generally the client/server setup is as simple as making sure that firewalls aren't blocking the port you are using. All comms is simple HTTP so there should be nothing special to do - the server is just running a simple HTTP endpoint. 

If you follow the server logs do you see all the requests getting through to the server?

**Comment by mylesdunlop** [comment]
@kal - I'm not sure if symptoms / failures are totally consistent, but I did get a repeatable example as per the steps below. I've tried to provide as much relevant information as possible.

What I observe from the log file entries generated from the steps below is:
a) Whereas on Polaris the 2nd update query timed out, the server log suggests that it succeeded.
b) Unexpectedly, the Job Id for the update query that timed out is the same as that of the previous update query that succeeded.

STEPS:
1) Start BrightstarDB Service on server VM

2) On the host (client), start Polaris and connect to 'Tester' DB running on server

3) Run this SPARQL query:
select ?x ?y ?z
where { ?x ?y ?z }
- This returns the result set of several pre-existing triples in the data store.

4) Run this SPARQL update query:
insert data 
{ 
<http://example/book10>
<http://purl.org/dc/elements/1.1/title>
"some title 10" 
}
- This query appeared to be successful

5) Run this (slightly modified) query:
insert data 
{ 
<http://example/book11>
<http://purl.org/dc/elements/1.1/title>
"some title 11" 
}
- After a long delay, Polaris reports:
   An error occurred while executing the SPARQL update.
HTTP GET to Tester/jobs/21219a02-67c5-4d26-bf4e-755e3e1fbcb4 failed. Could not process server response.
The operation has timed out

6) Re-run the same query as in step 3).
- After a long delay, Polaris repotrs:
BrightstarDB.Polaris.ViewModel.SparqlQueryException: An error occurred while executing the SPARQL query. ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at BrightstarDB.Client.BrightstarRestClient.AuthenticatedFormPost(String relativePath, IEnumerable`1 postBodyParameters, String acceptType)
   at BrightstarDB.Client.BrightstarRestClient.ExecuteQuery(String storeName, String queryExpression, IEnumerable`1 defaultGraphUris, Nullable`1 ifNotModifiedSince, SparqlResultsFormat resultsFormat, RdfFormat graphFormat, ISerializationFormat& streamFormat)
   at BrightstarDB.Client.BrightstarRestClient.ExecuteQuery(String storeName, String queryExpression, IEnumerable`1 defaultGraphUris, Nullable`1 ifNotModifiedSince, SparqlResultsFormat resultsFormat, RdfFormat graphFormat)
   at BrightstarDB.Client.BrightstarRestClient.ExecuteQuery(String storeName, String queryExpression, Nullable`1 ifNotModifiedSince, SparqlResultsFormat resultsFormat, RdfFormat graphFormat)
   at BrightstarDB.Polaris.ViewModel.Connection.<>c__DisplayClass61_0.<ExecuteQuery>b__0(IBrightstarService client)
   --- End of inner exception stack trace ---
   at BrightstarDB.Polaris.ViewModel.Connection.<>c__DisplayClass61_0.<ExecuteQuery>b__0(IBrightstarService client)
   at BrightstarDB.Polaris.ViewModel.Connection.WithClient[T](Func`2 func)
   at BrightstarDB.Polaris.ViewModel.Connection.ExecuteQuery(Store store, String sparqlQueryString, CommitPointViewModel targetCommitPoint)
   at BrightstarDB.Polaris.ViewModel.Store.ExecuteSparql(String sparqlQueryString, CommitPointViewModel targetCommitPoint)
   at BrightstarDB.Polaris.ViewModel.SparqlQueryViewModel.RunSparqlQuery(Object o)
   
7) Inspect the BrightstarDB server log file, see the following output:
BrightstarDB.Polaris.ViewModel.SparqlQueryException: An error occurred while executing the SPARQL query. ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at BrightstarDB.Client.BrightstarRestClient.AuthenticatedFormPost(String relativePath, IEnumerable`1 postBodyParameters, String acceptType)
   at BrightstarDB.Client.BrightstarRestClient.ExecuteQuery(String storeName, String queryExpression, IEnumerable`1 defaultGraphUris, Nullable`1 ifNotModifiedSince, SparqlResultsFormat resultsFormat, RdfFormat graphFormat, ISerializationFormat& streamFormat)
   at BrightstarDB.Client.BrightstarRestClient.ExecuteQuery(String storeName, String queryExpression, IEnumerable`1 defaultGraphUris, Nullable`1 ifNotModifiedSince, SparqlResultsFormat resultsFormat, RdfFormat graphFormat)
   at BrightstarDB.Client.BrightstarRestClient.ExecuteQuery(String storeName, String queryExpression, Nullable`1 ifNotModifiedSince, SparqlResultsFormat resultsFormat, RdfFormat graphFormat)
   at BrightstarDB.Polaris.ViewModel.Connection.<>c__DisplayClass61_0.<ExecuteQuery>b__0(IBrightstarService client)
   --- End of inner exception stack trace ---
   at BrightstarDB.Polaris.ViewModel.Connection.<>c__DisplayClass61_0.<ExecuteQuery>b__0(IBrightstarService client)
   at BrightstarDB.Polaris.ViewModel.Connection.WithClient[T](Func`2 func)
   at BrightstarDB.Polaris.ViewModel.Connection.ExecuteQuery(Store store, String sparqlQueryString, CommitPointViewModel targetCommitPoint)
   at BrightstarDB.Polaris.ViewModel.Store.ExecuteSparql(String sparqlQueryString, CommitPointViewModel targetCommitPoint)
   at BrightstarDB.Polaris.ViewModel.SparqlQueryViewModel.RunSparqlQuery(Object o)
   
8) The server log contains:
    DateTime=2018-02-20T11:07:53.1123906Z
BrightstarDB Information: 0 : Query Tester select ?x ?y ?z
where { ?x ?y ?z }
    DateTime=2018-02-20T11:07:53.1123906Z
BrightstarDB Information: 0 : Queueing Job Id 10671084-69c4-40ae-b9b9-71e9b180b8bc
    DateTime=2018-02-20T11:08:13.7217656Z
BrightstarDB Information: 0 : Queued Job Id 10671084-69c4-40ae-b9b9-71e9b180b8bc
    DateTime=2018-02-20T11:08:13.7217656Z
BrightstarDB Information: 0 : Job found 10671084-69c4-40ae-b9b9-71e9b180b8bc
    DateTime=2018-02-20T11:08:13.7373906Z
BrightstarDB Information: 0 : SPARQL update job being run on expression 'insert data 
{ 
<http://example/book10>
<http://purl.org/dc/elements/1.1/title>
"some title 10" 
}'
    DateTime=2018-02-20T11:08:13.7373906Z
BrightstarDB Information: 0 : Open Store C:\brightstar\Data\Tester
    DateTime=2018-02-20T11:08:13.7373906Z
BrightstarDB Information: 0 : Store C:\brightstar\Data\Tester opened successfully
    DateTime=2018-02-20T11:08:13.7373906Z
BrightstarDB Information: 0 : SPARQL update job completed successfully
    DateTime=2018-02-20T11:08:13.7686406Z
BrightstarDB Information: 0 : Job completed in 31.25 : Current memory usage : 68333568
    DateTime=2018-02-20T11:08:13.7686406Z
BrightstarDB Information: 0 : Queueing Job Id 21219a02-67c5-4d26-bf4e-755e3e1fbcb4
    DateTime=2018-02-20T11:08:22.2686406Z
BrightstarDB Information: 0 : Queued Job Id 21219a02-67c5-4d26-bf4e-755e3e1fbcb4
    DateTime=2018-02-20T11:08:22.2686406Z
BrightstarDB Information: 0 : Job found 21219a02-67c5-4d26-bf4e-755e3e1fbcb4
    DateTime=2018-02-20T11:08:22.2842656Z
BrightstarDB Information: 0 : SPARQL update job being run on expression 'insert data 
{ 
<http://example/book11>
<http://purl.org/dc/elements/1.1/title>
"some title 11" 
}'
    DateTime=2018-02-20T11:08:22.2842656Z
BrightstarDB Information: 0 : SPARQL update job completed successfully
    DateTime=2018-02-20T11:08:22.2998906Z
BrightstarDB Information: 0 : Job completed in 15.625 : Current memory usage : 68333568
    DateTime=2018-02-20T11:08:22.2998906Z
BrightstarDB Information: 0 : ServerCore Initialised C:\brightstar\Data\

9) I then started the BrightstarDB service (and Polaris on the client) repeated the above steps and the outcome was the same (I ran the SELECT query a couple of times before proceeding further). The complete server log for this session was:
BrightstarDB Information: 0 : ServerCore Initialised C:\brightstar\Data\
    DateTime=2018-02-20T11:50:51.0303594Z
BrightstarDB Information: 0 : List Stores
    DateTime=2018-02-20T11:50:57.0772344Z
BrightstarDB Information: 0 : check store exists store Tester
    DateTime=2018-02-20T11:51:47.5059453Z
BrightstarDB Information: 0 : Query Tester select ?x ?y ?z
where { ?x ?y ?z }
    DateTime=2018-02-20T11:51:47.5059453Z
BrightstarDB Information: 0 : check store exists store Tester
    DateTime=2018-02-20T11:51:47.5059453Z
BrightstarDB Information: 0 : StoreWorker created with location C:\brightstar\Data\Tester
    DateTime=2018-02-20T11:51:47.5059453Z
BrightstarDB Information: 0 : Query SELECT ?x ?y ?z WHERE
{ ?x ?y ?z . }

    DateTime=2018-02-20T11:51:47.5059453Z
BrightstarDB Information: 0 : Process Jobs Started
    DateTime=2018-02-20T11:51:47.5215703Z
BrightstarDB Information: 0 : Open Store C:\brightstar\Data\Tester
    DateTime=2018-02-20T11:51:47.5215703Z
BrightstarDB Information: 0 : Store C:\brightstar\Data\Tester opened successfully
    DateTime=2018-02-20T11:51:47.5528203Z
BrightstarDB Information: 0 : check store exists store Tester
    DateTime=2018-02-20T11:52:15.1231328Z
BrightstarDB Information: 0 : Query Tester select ?x ?y ?z
where { ?x ?y ?z }
    DateTime=2018-02-20T11:52:15.1231328Z
BrightstarDB Information: 0 : Queueing Job Id 450205bc-c2e6-467d-9fc5-f2a58341bbfb
    DateTime=2018-02-20T11:52:47.3887578Z
BrightstarDB Information: 0 : Queued Job Id 450205bc-c2e6-467d-9fc5-f2a58341bbfb
    DateTime=2018-02-20T11:52:47.3887578Z
BrightstarDB Information: 0 : Job found 450205bc-c2e6-467d-9fc5-f2a58341bbfb
    DateTime=2018-02-20T11:52:47.4043828Z
BrightstarDB Information: 0 : SPARQL update job being run on expression 'insert data 
{ 
<http://example/book12>
<http://purl.org/dc/elements/1.1/title>
"some title 12" 
}'
    DateTime=2018-02-20T11:52:47.4043828Z
BrightstarDB Information: 0 : Open Store C:\brightstar\Data\Tester
    DateTime=2018-02-20T11:52:47.4043828Z
BrightstarDB Information: 0 : Store C:\brightstar\Data\Tester opened successfully
    DateTime=2018-02-20T11:52:47.4043828Z
BrightstarDB Information: 0 : SPARQL update job completed successfully
    DateTime=2018-02-20T11:52:47.4356328Z
BrightstarDB Information: 0 : Job completed in 31.25 : Current memory usage : 67121152
    DateTime=2018-02-20T11:52:47.4356328Z
BrightstarDB Information: 0 : Queueing Job Id e62057a2-8f73-48a4-a905-80f2abed4867
    DateTime=2018-02-20T11:53:09.3262578Z
BrightstarDB Information: 0 : Queued Job Id e62057a2-8f73-48a4-a905-80f2abed4867
    DateTime=2018-02-20T11:53:09.3262578Z
BrightstarDB Information: 0 : Job found e62057a2-8f73-48a4-a905-80f2abed4867
    DateTime=2018-02-20T11:53:09.3418828Z
BrightstarDB Information: 0 : SPARQL update job being run on expression 'insert data 
{ 
<http://example/book13>
<http://purl.org/dc/elements/1.1/title>
"some title 13" 
}'
    DateTime=2018-02-20T11:53:09.3418828Z
BrightstarDB Information: 0 : SPARQL update job completed successfully
    DateTime=2018-02-20T11:53:09.3418828Z
BrightstarDB Information: 0 : Job completed in 0 : Current memory usage : 67506176
    DateTime=2018-02-20T11:53:09.3418828Z
